# Generated by Django 5.2.7 on 2025-11-15 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('especialidad', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'medico',
            },
        ),
        migrations.CreateModel(
            name='PacienteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=9)),
                ('correo', models.EmailField(max_length=150)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='ExpedienteModel',
            fields=[
                ('id_expediente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('descripcion', models.TextField()),
                ('fk_paciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appMedic.pacientemodel')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioMedicoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('fk_medico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='horarios', to='appMedic.medicomodel')),
            ],
            options={
                'verbose_name': 'Horario Médico',
                'verbose_name_plural': 'Horarios Médicos',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('fk_medico', 'dia_semana', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='AgendaModel',
            fields=[
                ('id_agenda', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('fk_medico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='agendas', to='appMedic.medicomodel')),
                ('fk_paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMedic.pacientemodel')),
            ],
            options={
                'unique_together': {('fk_medico', 'fecha', 'hora_inicio')},
            },
        ),
    ]
