# Generated by Django 4.2 on 2025-11-18 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('especialidad', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
        migrations.CreateModel(
            name='PacienteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=9)),
                ('correo', models.EmailField(max_length=150)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='HorarioMedicoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('fk_medico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='horarios', to='appMedic.medicomodel')),
            ],
            options={
                'verbose_name': 'Horario Médico',
                'verbose_name_plural': 'Horarios Médicos',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('fk_medico', 'dia_semana', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='ExpedienteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fk_paciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appMedic.pacientemodel')),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
            },
        ),
        migrations.CreateModel(
            name='AgendaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('disponible', models.BooleanField(default=True)),
                ('fk_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_agendadas', to='appMedic.horariomedicomodel')),
                ('fk_paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMedic.pacientemodel')),
            ],
            options={
                'ordering': ['fecha', 'fk_horario__hora_inicio'],
                'unique_together': {('fk_horario', 'fecha')},
            },
        ),
    ]
