# Generated by Django 4.2 on 2025-11-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMedic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('tipo_usuario', models.CharField(choices=[('paciente', 'Paciente'), ('medico', 'Médico'), ('admin', 'Administrador')], default='paciente', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
